### ISSUE TITLE
실종동물 게시판 엔티티 작성

### ISSUE THREAD

**Issue by devsince2021** [SesacAcademy/SesacAnimal#8]
- [x] 실종동물 게시판 엔티티 작성

**Comment by akgkfk3** [comment]
@devsince2021  [[링크]](https://github.com/SesacAcademy/SesacAnimal/blob/dev/src/main/java/com/project/animal/missing/domain/MissingPost.java#L16)

해당 엔티티 클래스에 '@ToString' 어노테이션은 순환 참조 발생할 여지가 있어서 되도록이면 안 쓰고자 하는데 혹시 이유가 있을까요?

추가적으로 게시판 엔티티에서 댓글 엔티티를 List 형태로 참조했으면 합니다 (ManyToOne)

**Comment by devsince2021** [comment]
@akgkfk3 
리뷰해주셔서 감사합니다!

지금 만들어놓은 엔티티는 오늘 뷰작업에 쓰일 더미 데이터 생성하는데 쓰려고 만들었습니다.
제대로 생성되나 확인하려고 toString 달아서 사용했는데 @toString은 제거 하도록하겠습니다~

게시판만 crud > 이미지 추가 > 댓글 crud 하는 방향으로 작업을 하려고 생각하고 있습니다.
이후에 댓글 작업할 때 ManyToOne 참조걸 수 있도록 하겠습니다
